// <auto-generated />
namespace CodeFast.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class QuantityRemoved_Product : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QuantityRemoved_Product));
        
        string IMigrationMetadata.Id
        {
            get { return "202104011414220_QuantityRemoved_Product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
