//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;
using System.Xml.Serialization;

namespace APIdbWithRipo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catagory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catagory()
        {
            this.Products = new HashSet<Product>();
        }

        List<Link> links = new List<Link>();
       // public List<Link>Links { get; set; }

        public List<Link> Links
        {
            get { return links; }
        }



        public int CatagoriesId { get; set; }
        public string CatagoriesName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        
       [JsonIgnore,XmlIgnore] //to ignore looping and product data
        public virtual ICollection<Product> Products { get; set; }
    }
}
