//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ch24ShoppingCartMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class LineItem
    {
        public int InvoiceNumber { get; set; }
        public string ProductID { get; set; }
        public decimal UnitPrice { get; set; }

        [Required, Range(2, 1000)]
        public int Quantity { get; set; }
        public Nullable<decimal> Extension { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Product Product { get; set; }
    }
}
