//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductsId { get; set; }
        public string ProductsName { get; set; }
        public Nullable<int> Price { get; set; }
        public int CatagoriesId { get; set; }
    
        public virtual Catagory Catagory { get; set; }
    }
}
